server:
  port: 8083

spring:
  profiles:
    active: dev
    include: website,alipay,oss,fastdfs,paypal


  rabbitmq:
    enable: 0
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /novel-plus
    template:
      # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      exchange: novel.exchange
    publisher-confirms: false


  elasticsearch:
    #是否开启搜索引擎，1：开启，0：不开启
    enable: 0
    jest:
      uris: http://192.168.0.105:9200



redisson:
  singleServerConfig:
    address: 127.0.0.1:6379

jwt:
  secret: novel!#20191230
  expiration: 604800

#缓存管理密码
cache:
  manager:
    password: novel@2020117


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接 （多个用逗号分隔）
  urlPatterns: /book/addBookComment,/user/addFeedBack,/author/addBook,/author/addBookContent,/author/updateBookContent,/author/register.html

pic:
  save:
    type: 1 #图片保存方式, 1不保存，使用爬取的网络图片 ，2保存在自己的存储介质
    storage: local #存储介质，local：本地，OSS：阿里云对象存储，fastDfs：分布式文件系统
    path: /var/pic  #图片保存路径

author:
  income:
    #税率(扣税后所得比率)
    tax-rate: 0.9
    #分佣比例
    share-proportion: 0.7
    #兑换比率(人民币)
    exchange-proportion: 0.01

#小说章节定价规则
book:
  price:
    #字数
    word-count: 1000
    #价值(屋币)
    value: 5








