spring:
  profiles:
    include: [common-dev]


#线程池配置
thread:
  pool:
    #核心线程池数量
    core-pool-size: 10
    #最大线程池数量
    maximum-pool-size: 20
    #线程超时时间（秒）
    keep-alive-time: 10
    #队列大小
    queue-size: 100